### ISSUE TITLE
nuget package dlls require breeze client

### ISSUE THREAD

**Issue by flyfishMT** [Breeze/bower-breeze-client#1]
I'd like to move to manage the breeze-client with bower with the work done here. However, I have a .NET backend that uses nuget to manage the .net code.  It also installs "Breeze.Client" in nuget.  I can't uninstall breeze client code in nuget because of nuget deps: "Unable to uninstall 'Breeze.Client.1.6.0' because 'Breeze.WebApi2.EF6.1.6.0' depends on it."  I know this isn't an issue with the bower setup but with the nuget package, but is a change that might need to occur for people to switch to the bower package?

**Comment by marcelgood** [comment]
You should use the following three NuGet packages on the server instead. These packages include all the server code, but won't install the client library. 

Breeze.Server.ContextProvider
Breeze.Server.ContextProvider.EF6
Breeze.Server.WebApi2

As for the client, we recommend you use npm and not bower. Here's an Angular 2 reference example that uses NuGet for all the .NET packages and npm for all the client packages.

https://github.com/Breeze/temphire.angular2

**Comment by flyfishMT** [comment]
Thanks I will take a look why do you recommend npm over bower for client packages?

**Comment by marcelgood** [comment]
Pretty much everybody is going with npm. It's become the package manager for TypeScript and pretty much everything is happening with npm these days. I don't hear much about bower anymore. We try to keep the breeze bower package updated, but don't do it all the time. You'll always find the latest version of Breeze in npm, though. If you do consider TypeScript at some point, the type definitions are distributed via npm as well.

**Comment by flyfishMT** [comment]
Thanks. It does look like the way to go but the thing I don't like with using npm is still you get "all of node" in the node_modules directory and with a browser based app, I don't want all those files in my deployment/distribution. I couldn't find a very robust build process to grab the "main files" either.

**Comment by marcelgood** [comment]
That's where application bundling comes in with tools such as Webpack. Webpack will figure out all the dependencies and include what the app needs in one or more bundles. Then you only deploy the bundle(s). The node_modules folder is only needed during development and the build and will never get deployed. 

Not sure what technology stack you are using and how your app is structured, but here's an example of a modern Angular 2 app with Breeze. It uses rollup.js to bundle the app into a single `build.js` script. This script includes all the required dependencies from the `node_modules` folder along with the application code. There are still a handful of scripts and stylesheets statically loaded in `index.html`, but those would be easy to gather during the build process and put into a distribution folder. 

https://github.com/Breeze/temphire.angular2
